<?php

declare(strict_types=1);

/**
 * Nomi delle nazioni in italiano, per codice ISO 3166-1 alpha-3.
 *
 * Il Factbook li fornisce solo in inglese (e per qualche Stato nemmeno quello:
 * la "conventional short form" a volte manca). Questa tabella è nostra e va
 * riletta: è l'unico pezzo del seme che nessuna fonte può verificare al posto
 * nostro.
 */

return [
    'AFG' => 'Afghanistan',            'AGO' => 'Angola',
    'ALB' => 'Albania',                'AND' => 'Andorra',
    'ARE' => 'Emirati Arabi Uniti',    'ARG' => 'Argentina',
    'ARM' => 'Armenia',                'ATG' => 'Antigua e Barbuda',
    'AUS' => 'Australia',              'AUT' => 'Austria',
    'AZE' => 'Azerbaigian',            'BDI' => 'Burundi',
    'BEL' => 'Belgio',                 'BEN' => 'Benin',
    'BFA' => 'Burkina Faso',           'BGD' => 'Bangladesh',
    'BGR' => 'Bulgaria',               'BHR' => 'Bahrein',
    'BHS' => 'Bahamas',                'BIH' => 'Bosnia ed Erzegovina',
    'BLR' => 'Bielorussia',            'BLZ' => 'Belize',
    'BOL' => 'Bolivia',                'BRA' => 'Brasile',
    'BRB' => 'Barbados',               'BRN' => 'Brunei',
    'BTN' => 'Bhutan',                 'BWA' => 'Botswana',
    'CAF' => 'Repubblica Centrafricana','CAN' => 'Canada',
    'CHE' => 'Svizzera',               'CHL' => 'Cile',
    'CHN' => 'Cina',                   'CIV' => "Costa d'Avorio",
    'CMR' => 'Camerun',                'COD' => 'Repubblica Democratica del Congo',
    'COG' => 'Repubblica del Congo',   'COL' => 'Colombia',
    'COM' => 'Comore',                 'CPV' => 'Capo Verde',
    'CRI' => 'Costa Rica',             'CUB' => 'Cuba',
    'CYP' => 'Cipro',                  'CZE' => 'Cechia',
    'DEU' => 'Germania',               'DJI' => 'Gibuti',
    'DMA' => 'Dominica',               'DNK' => 'Danimarca',
    'DOM' => 'Repubblica Dominicana',  'DZA' => 'Algeria',
    'ECU' => 'Ecuador',                'EGY' => 'Egitto',
    'ERI' => 'Eritrea',                'ESP' => 'Spagna',
    'EST' => 'Estonia',                'ETH' => 'Etiopia',
    'FIN' => 'Finlandia',              'FJI' => 'Figi',
    'FRA' => 'Francia',                'FSM' => 'Micronesia',
    'GAB' => 'Gabon',                  'GBR' => 'Regno Unito',
    'GEO' => 'Georgia',                'GHA' => 'Ghana',
    'GIN' => 'Guinea',                 'GMB' => 'Gambia',
    'GNB' => 'Guinea-Bissau',          'GNQ' => 'Guinea Equatoriale',
    'GRC' => 'Grecia',                 'GRD' => 'Grenada',
    'GTM' => 'Guatemala',              'GUY' => 'Guyana',
    'HND' => 'Honduras',               'HRV' => 'Croazia',
    'HTI' => 'Haiti',                  'HUN' => 'Ungheria',
    'IDN' => 'Indonesia',              'IND' => 'India',
    'IRL' => 'Irlanda',                'IRN' => 'Iran',
    'IRQ' => 'Iraq',                   'ISL' => 'Islanda',
    'ISR' => 'Israele',                'ITA' => 'Italia',
    'JAM' => 'Giamaica',               'JOR' => 'Giordania',
    'JPN' => 'Giappone',               'KAZ' => 'Kazakistan',
    'KEN' => 'Kenya',                  'KGZ' => 'Kirghizistan',
    'KHM' => 'Cambogia',               'KIR' => 'Kiribati',
    'KNA' => 'Saint Kitts e Nevis',    'KOR' => 'Corea del Sud',
    'KWT' => 'Kuwait',                 'LAO' => 'Laos',
    'LBN' => 'Libano',                 'LBR' => 'Liberia',
    'LBY' => 'Libia',                  'LCA' => 'Santa Lucia',
    'LKA' => 'Sri Lanka',              'LSO' => 'Lesotho',
    'LTU' => 'Lituania',               'LUX' => 'Lussemburgo',
    'LVA' => 'Lettonia',               'MAR' => 'Marocco',
    'MDA' => 'Moldavia',               'MDG' => 'Madagascar',
    'MDV' => 'Maldive',                'MEX' => 'Messico',
    'MHL' => 'Isole Marshall',         'MKD' => 'Macedonia del Nord',
    'MLI' => 'Mali',                   'MLT' => 'Malta',
    'MMR' => 'Birmania',               'MNE' => 'Montenegro',
    'MNG' => 'Mongolia',               'MOZ' => 'Mozambico',
    'MRT' => 'Mauritania',             'MUS' => 'Mauritius',
    'MWI' => 'Malawi',                 'MYS' => 'Malaysia',
    'NAM' => 'Namibia',                'NER' => 'Niger',
    'NGA' => 'Nigeria',                'NIC' => 'Nicaragua',
    'NLD' => 'Paesi Bassi',
    'NOR' => 'Norvegia',               'NPL' => 'Nepal',
    'NZL' => 'Nuova Zelanda',          'OMN' => 'Oman',
    'PAK' => 'Pakistan',               'PAN' => 'Panama',
    'PER' => 'Perù',                   'PHL' => 'Filippine',
    'PNG' => 'Papua Nuova Guinea',     'POL' => 'Polonia',
    'PRK' => 'Corea del Nord',         'PRT' => 'Portogallo',
    'PRY' => 'Paraguay',               'QAT' => 'Qatar',
    'ROU' => 'Romania',                'RUS' => 'Russia',
    'RWA' => 'Ruanda',                 'SAU' => 'Arabia Saudita',
    'SDN' => 'Sudan',                  'SEN' => 'Senegal',
    'SGP' => 'Singapore',              'SLB' => 'Isole Salomone',
    'SLE' => 'Sierra Leone',           'SLV' => 'El Salvador',
    'SOM' => 'Somalia',                'SRB' => 'Serbia',
    'SSD' => 'Sud Sudan',              'STP' => 'São Tomé e Príncipe',
    'SUR' => 'Suriname',               'SVK' => 'Slovacchia',
    'SVN' => 'Slovenia',               'SWE' => 'Svezia',
    'SWZ' => 'Eswatini',               'SYC' => 'Seychelles',
    'SYR' => 'Siria',                  'TCD' => 'Ciad',
    'TGO' => 'Togo',                   'THA' => 'Thailandia',
    'TJK' => 'Tagikistan',             'TKM' => 'Turkmenistan',
    'TLS' => 'Timor Est',              'TON' => 'Tonga',
    'TTO' => 'Trinidad e Tobago',      'TUN' => 'Tunisia',
    'TUR' => 'Turchia',                'TWN' => 'Taiwan',
    'TZA' => 'Tanzania',               'UGA' => 'Uganda',
    'UKR' => 'Ucraina',                'URY' => 'Uruguay',
    'USA' => 'Stati Uniti',            'UZB' => 'Uzbekistan',
    'VCT' => 'Saint Vincent e Grenadine', 'VEN' => 'Venezuela',
    'VNM' => 'Vietnam',                'VUT' => 'Vanuatu',
    'WSM' => 'Samoa',                  'XKX' => 'Kosovo',
    'YEM' => 'Yemen',                  'ZAF' => 'Sudafrica',
    'ZMB' => 'Zambia',                 'ZWE' => 'Zimbabwe',
];
